# Generated by Django 3.1.7 on 2021-07-05 07:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'SINGLE_CHOICE'), ('MULTI_CHOICES', 'MULTI_CHOICES'), ('CONSTRUCTED_RESPONSES', 'CONSTRUCTED_RESPONSES'), ('MULTI_QUESTIONS', 'MULTI_QUESTIONS')], default='SINGLE_CHOICE', max_length=30)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('WELLKNOWN', 'WELLKNOWN'), ('MASTERED', 'MASTERED')], default='EASY', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('true_choices', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='questions.question')),
            ],
        ),
    ]
